### ISSUE TITLE
Clean up email data being sent to client

### ISSUE THREAD

**Issue by nlokare** [hesitant-tapdancers/gilded#182]
Send over as structured JSON instead of messy string

**Comment by dsernst** [comment]
Right now we are storing the email bodies as full strings, because that's what SendGrid is giving us and that's what it's expecting back. These need to be JSON parse'd before they can be displayed in the front-end, but it makes more sense to do that on the client then add the load to the server, which doesn't give any advantage.

Later, we might want to consider parsing these emails before they ever get stored into the database, so that we can more advanced filtering before sending them to the client, e.g. filtering by "from:", or "subject:". But instead of pre-maturely optimizing we can leave this how it is for now until we need to more efficiently filter.
