### ISSUE TITLE
Debug live application

### ISSUE THREAD

**Issue by nlokare** [hesitant-tapdancers/gilded#216]
Sign up operation is failing

**Comment by dsernst** [comment]
we fixed it. the Stripe_id field was set to `unique: true`, which was throwing a `Duplicate error` when they signed up because it was getting set to `null` by default.

Even changing the Mongoose schema wasn't fixing it. We had to manually go in and update the Mongo indexes, as described here: http://stackoverflow.com/a/13454765/2348750
